### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by wzurborg** [HughMahoney/probabilityDist#2]
Hi, thanks for your python module. Can you add installation requirements and/or instructions on how to include the required libraries please. Trying to execute your script with a basic Python interpreter ends up with 

```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by hm0809** [comment]
In a future update I'll be making a GUI which will require a module installation (file structure: e.g. init.py, setup.py, requirements.txt). Right now since it is a stand-alone script it would be take away its simplicity by introducing a file-structure that may confuse people who don't usually run python programs. 

What I will do in the mean time is create some instructions on how to install the required modules using pip. In regards to your specific situation - you will want to install pandas using pip. Run the command `pip3 install pandas`, as well as `pip install __module__` for any other dependencies that you don't already have installed.


Thanks for the suggestion, it is very much appreciated.
